### PR TITLE
Complete restaurant project with the required features.

### PR DESCRIPTION
**Pull request by Zibilyonik**
The project is completed with the features listed below:
-Fully based on JS
-Tab buttons allowing for the website to switch between content as desired.
-A working implementation of webpack and nodes.

### CODE REVIEW

**Review by trekab — COMMENTED** [review]
### Invalid! :stop_sign: 
Hi @Zibilyonik! Unfortunately, I have to invalidate your PR because you didn't set up linting for your project. ([Read more](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-))

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__[Treasure Kabareebe](https://trekab.github.io)__

**Review by trekab — COMMENTED** [review]
### Invalid! :stop_sign: 
Hi @Zibilyonik! Unfortunately, I have to invalidate your project because it doesn't meet the professional repo guidelines provided [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Please use the `README` template provided [here](https://github.com/microverseinc/readme-template) to make your `README` more descriptive.

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__[Treasure Kabareebe](https://trekab.github.io)__

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED🛑🛑🛑**

Hello @Zibilyonik 
Great work on this project. You implemented in a simple and effective way and it is working👏👏.

Let's make small changes and get it approved.

[REQUIRED]: Kindly add this to your package.json so that you can run commands like `npm start` to start the project instead of right click on the index.html.
`"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  }
`
[REQUIRED]: Kindly use arrow functions to effectively use ES6.

That's it.
Make the requested changes and ask for another review👍👍

Happy coding💻💻

**Review by mke2111 — APPROVED** [review]
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. ES6 arrow functions are used appropriately.
    2. The scripts are clear
    

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Pull request merged**
